// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "1a459c58-0ab8-47cf-bf92-dae9dc22daaf");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1696731638);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1696731636);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{abd9868a-9ffd-41c7-8771-5e7cc2043ba5}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1696731631);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 139);
user_pref("browser.newtabpage.activity-stream.impressionId", "{bf7a8e2a-ff69-44b9-bb9c-84a7619c577b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1696731639957");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1696753239957");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1696731635");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230928054334");
user_pref("browser.startup.homepage_override.mstone", "118.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1696731633);
user_pref("browser.topsites.contile.cacheValidFor", 10401);
user_pref("browser.topsites.contile.cachedTiles", "[{\"id\":74301,\"name\":\"Amazon\",\"url\":\"https://www.amazon.com/?tag=admarketus-20&ref=pd_sl_d0145a3d02e1e859f565ad88b504b5043fcb7e1057cc0d73e154bd3d&mfadid=adm\",\"click_url\":\"https://bridge.sfo1.ap01.net/ctp?version=16.0.0&key=1696730718400500002.1&ci=1696730718667.12791&ctag=pd_sl_d0145a3d02e1e859f565ad88b504b5043fcb7e1057cc0d73e154bd3d\",\"image_url\":\"https://contile-images.services.mozilla.com/obgoOYObjIFea_bXuT6L4LbBJ8j425AD87S1HMD3BWg.9991.jpg\",\"image_size\":200,\"impression_url\":\"https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4Qqm4ZfW4Zla4pbW4CbWfpbY7ReNxR3UIG8zInwYIFIVs9eYiGINHrwkiFXwxYIZjF8XgClWfC2X7R4dHQ8zJnErj%3DcO7R4dHQfz4Z2ZfplnHG3Z5FwqgCfX1p8d4Cxr1BINI9HuiF2z4Z2ZfplnHmcux%3DcvImauiF2zfQlWfp2%2B7ncqIr7VjGbuiF2zfCfk4Qxr4Qfnj9wWIBdvIpkY7R4TJr2uJREuHnEYgClnHr7wHG3vjnDuiF2zfCbY4BIWJ%3DcQIFdwJR2uiF2zfCbW4Wyy\"},{\"id\":75033,\"name\":\"T-Mobile\",\"url\":\"https://www.t-mobile.com/cell-phones/brand/apple?cmpid=MGPO_PAM_P_EVGRNIPHN_{_dstrackerid}_1696730718400500002&mfadid=adm\",\"click_url\":\"https://bridge.sfo1.admarketplace.net/ctp?version=16.0.0&key=1696730718400500002.2&ci=1696730718667.12791&ctag=1696730718400500002\",\"image_url\":\"https://contile-images.services.mozilla.com/T23eBL4EHswiSaF6kya2gYsRHvdfADK-NYjs1mVRNGE.3351.jpg\",\"image_size\":200,\"impression_url\":\"https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4Qqm4ZfW4Zla4pbW4CbWfpbY7ReNxR3UIG8zInwYIFIVs9eYiGINHrwkiFXwxYIZjF8XgClWfC2X7R4dHQ8zJnErj%3DcO7R4dHQfz4ZDWfZfnHG3Z5FwqgCfX1p8d4Cxr1BINI9HuiF2z4ZDWfZfnHmcux%3DcvImauiF2zfQ8WfQLr7ncqIr7VjGbuiF2zfCDk1p8ZfZfnj9wWIBdvIpkY7R4TJr2uJREuHnEYgC8nHr7wHG3vjnDuiF2z4Zfd1BIWJ%3DcQIFdwJR2uiF2zfCbW4Wyy\"}]");
user_pref("browser.topsites.contile.lastFetch", 1696731635);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1696731635305");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "118.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "a9e010b59b8f4f0f8e67d63177150f4d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230928054334");
user_pref("extensions.lastAppVersion", "118.0.1");
user_pref("extensions.lastPlatformVersion", "118.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"22fcbd77-eb2c-4809-ae50-245ef087f081\",\"pictureinpicture@mozilla.org\":\"e2b96387-25db-4d62-bb90-82785c70d854\",\"screenshots@mozilla.org\":\"24b926b2-dfec-48c2-8c2a-3441d8ef985e\",\"webcompat-reporter@mozilla.org\":\"9ca12414-ea84-4f49-976a-1d31f8ccdb96\",\"webcompat@mozilla.org\":\"aa3db2dc-71e4-48dc-9714-a5bb1e67b116\",\"default-theme@mozilla.org\":\"538ef6ee-57d8-491b-af14-37467e3d5728\",\"addons-search-detection@mozilla.com\":\"42e21a36-b749-4365-b8d6-2028c2de5132\",\"google@search.mozilla.org\":\"b20bbacf-27cd-4c40-baa6-40ad7404f94f\",\"amazondotcom@search.mozilla.org\":\"348422eb-9c5c-48ff-acc8-100033ead96a\",\"wikipedia@search.mozilla.org\":\"123383fa-918d-48f9-83d0-15608a28496f\",\"bing@search.mozilla.org\":\"effdc522-832a-442a-91c7-8ece8bf35a3a\",\"ddg@search.mozilla.org\":\"83b8f809-9e7b-49dc-9dbc-f278a59060c4\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"enrollmentId\":\"2a8a8ccb-c6c8-4ac9-ab46-f19e6b11a6b0\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2023-10-08T02:20:36.092Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f5858391-cb8d-452e-90b9-1572fc205d57");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1696731620);
user_pref("toolkit.telemetry.cachedClientID", "d7feae13-7cfc-4776-ab38-f5abfb66036b");
user_pref("toolkit.telemetry.previousBuildID", "20230928054334");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
